# this file was automatically generated by /data/familiars/run.sh
# do not edit, edit the scraper
import sys
from datautils import percent
from common import *

familiars = {
  FAMILIAR: {
    FAMILIAR_STATS: percent({
      BASE: [
        [FLAT_MAINSTAT_A, 5.882], # STR: +1
      ],
      COMMON: [
        [IED_C, 0.617], # Attacks ignore 15% Monster DEF
        [SMALL_DROP, 1.235], # Increases Item Drop Rate by a small amount (30)
        [SMALL_MESO, 1.235], # Increases Meso Drop Rate by a small amount (30)
        [FLAT_MAINSTAT_A, 2.469], # STR: +2
        [FLAT_MAINSTAT_B, 2.469], # STR: +1
        [DAMAGE_A, 0.37], # Total Damage: +1%
      ],
      RARE: [
        [IED_C, 0.264], # Attacks ignore 15% Monster DEF
        [DROP_A, 0.88], # Increases Item Drop Rate (50)
        [SMALL_DROP, 0.88], # Increases Item Drop Rate by a small amount (30)
        [SMALL_DROP_MESO, 0.88], # Increases Item and Meso Drop Rate by a small amount (20)
        [MESO_A, 0.88], # Increases Meso Drop Rate (50)
        [SMALL_MESO, 0.88], # Increases Meso Drop Rate by a small amount (30)
        [FLAT_MAINSTAT_A, 1.759], # STR: +4
        [FLAT_MAINSTAT_B, 1.759], # STR: +3
        [DAMAGE_A, 0.264], # Total Damage: +2%
        [INVIN, 0.44], # When hit, get +1 sec of invincibility
      ],
      EPIC: [
        [IED_A, 0.22], # Attacks ignore 30% Monster DEF
        [IED_C, 0.22], # Attacks ignore 20% Monster DEF
        [BOSS_C, 0.147], # Damage to Bosses: +20%
        [BOSS_A, 0.147], # Damage to Bosses: +30%
        [DROP_A, 0.734], # Increases Item Drop Rate (60)
        [LARGE_DROP, 0.734], # Increases Item Drop Rate by a large amount (100)
        [DROP_MESO, 0.734], # Increases Item and Meso Drop Rate (40)
        [SMALL_DROP_MESO, 0.734], # Increases Item and Meso Drop Rate by a small amount (25)
        [MESO_A, 0.734], # Increases Meso Drop Rate (60)
        [LARGE_MESO, 0.734], # Increases Meso Drop Rate by a large amount (100)
        [FLAT_MAINSTAT_A, 1.468], # STR: +6
        [FLAT_MAINSTAT_B, 1.468], # STR: +5
        [DAMAGE_A, 0.22], # Total Damage: +3%
        [INVIN, 0.367], # When hit, get +2 sec of invincibility
      ],
      UNIQUE: [
        [IED_B, 0.219], # Attacks ignore 35% Monster DEF
        [IED_A, 0.219], # Attacks ignore 40% Monster DEF
        [IED_C, 0.219], # Attacks ignore 30% Monster DEF
        [BOSS_C, 0.146], # Boss Damage: +30%
        [BOSS_B, 0.146], # Boss Damage: +35%
        [BOSS_A, 0.146], # Boss Damage: +40%
        [CRITDMG_A, 0.438], # Critical Damage: +3%
        [CRITDMG_B, 0.438], # Critical Damage: +2%
        [LARGE_DROP_MESO, 0.73], # Increases Item and Meso Drop Rate by a large amount (50)
        [SMALL_DROP, 0.365], # Item Acquisition Rate: +10%
        [FLAT_MESO, 0.365], # Mesos Obtained: +10
        [FLAT_MAINSTAT_A, 1.46], # STR: +8
        [FLAT_MAINSTAT_B, 1.46], # STR: +7
        [DAMAGE_A, 0.219], # Total Damage: +6%
        [DAMAGE_B, 0.219], # Total Damage: +5%
        [INVIN, 0.365], # When hit, gain +3 sec of invincibility
      ],
      LEGENDARY: [
        [IED_B, 1.456], # Attacks ignore 45% Monster DEF
        [IED_A, 1.456], # Attacks ignore 50% Monster DEF
        [BOSS_C, 0.971], # Boss Damage: +40%
        [BOSS_B, 0.971], # Boss Damage: +45%
        [BOSS_A, 0.971], # Boss Damage: +50%
        [CRITDMG_A, 2.912], # Critical Damage: +6%
        [SMALL_DROP, 2.427], # Item Acquisition Rate: +12%
        [FLAT_MESO, 2.427], # Mesos Obtained: +12
        [DAMAGE_A, 1.456], # Total Damage: +9%
        [INVIN, 2.427], # When hit, gain +4 sec of invincibility
      ],
    }),
  },
}

values = {
  BASE: {
    ANY: 1,
    FLAT_MAINSTAT_A: 1,
  },
  COMMON: {
    ANY: 1,
    IED_C: 15,
    SMALL_DROP: 30,
    SMALL_MESO: 30,
    FLAT_MAINSTAT_A: 2,
    FLAT_MAINSTAT_B: 1,
    DAMAGE_A: 1,
  },
  RARE: {
    ANY: 1,
    IED_C: 15,
    DROP_A: 50,
    SMALL_DROP: 30,
    SMALL_DROP_MESO: 20,
    MESO_A: 50,
    SMALL_MESO: 30,
    FLAT_MAINSTAT_A: 4,
    FLAT_MAINSTAT_B: 3,
    DAMAGE_A: 2,
    INVIN: 1,
  },
  EPIC: {
    ANY: 1,
    IED_A: 30,
    IED_C: 20,
    BOSS_C: 20,
    BOSS_A: 30,
    DROP_A: 60,
    LARGE_DROP: 100,
    DROP_MESO: 40,
    SMALL_DROP_MESO: 25,
    MESO_A: 60,
    LARGE_MESO: 100,
    FLAT_MAINSTAT_A: 6,
    FLAT_MAINSTAT_B: 5,
    DAMAGE_A: 3,
    INVIN: 2,
  },
  UNIQUE: {
    ANY: 1,
    IED_B: 35,
    IED_A: 40,
    IED_C: 30,
    BOSS_C: 30,
    BOSS_B: 35,
    BOSS_A: 40,
    CRITDMG_A: 3,
    CRITDMG_B: 2,
    LARGE_DROP_MESO: 50,
    SMALL_DROP: 10,
    FLAT_MESO: 10,
    FLAT_MAINSTAT_A: 8,
    FLAT_MAINSTAT_B: 7,
    DAMAGE_A: 6,
    DAMAGE_B: 5,
    INVIN: 3,
  },
  LEGENDARY: {
    ANY: 1,
    IED_B: 45,
    IED_A: 50,
    BOSS_C: 40,
    BOSS_B: 45,
    BOSS_A: 50,
    CRITDMG_A: 6,
    SMALL_DROP: 12,
    FLAT_MESO: 12,
    DAMAGE_A: 9,
    INVIN: 4,
  },
}

desc = {
  BASE: {
    FLAT_MAINSTAT_A: "STR: +1",
  },
  COMMON: {
    IED_C: "Attacks ignore 15% Monster DEF",
    SMALL_DROP: "Increases Item Drop Rate by a small amount (30)",
    SMALL_MESO: "Increases Meso Drop Rate by a small amount (30)",
    FLAT_MAINSTAT_A: "STR: +2",
    FLAT_MAINSTAT_B: "STR: +1",
    DAMAGE_A: "Total Damage: +1%",
  },
  RARE: {
    IED_C: "Attacks ignore 15% Monster DEF",
    DROP_A: "Increases Item Drop Rate (50)",
    SMALL_DROP: "Increases Item Drop Rate by a small amount (30)",
    SMALL_DROP_MESO: "Increases Item and Meso Drop Rate by a small amount (20)",
    MESO_A: "Increases Meso Drop Rate (50)",
    SMALL_MESO: "Increases Meso Drop Rate by a small amount (30)",
    FLAT_MAINSTAT_A: "STR: +4",
    FLAT_MAINSTAT_B: "STR: +3",
    DAMAGE_A: "Total Damage: +2%",
    INVIN: "When hit, get +1 sec of invincibility",
  },
  EPIC: {
    IED_A: "Attacks ignore 30% Monster DEF",
    IED_C: "Attacks ignore 20% Monster DEF",
    BOSS_C: "Damage to Bosses: +20%",
    BOSS_A: "Damage to Bosses: +30%",
    DROP_A: "Increases Item Drop Rate (60)",
    LARGE_DROP: "Increases Item Drop Rate by a large amount (100)",
    DROP_MESO: "Increases Item and Meso Drop Rate (40)",
    SMALL_DROP_MESO: "Increases Item and Meso Drop Rate by a small amount (25)",
    MESO_A: "Increases Meso Drop Rate (60)",
    LARGE_MESO: "Increases Meso Drop Rate by a large amount (100)",
    FLAT_MAINSTAT_A: "STR: +6",
    FLAT_MAINSTAT_B: "STR: +5",
    DAMAGE_A: "Total Damage: +3%",
    INVIN: "When hit, get +2 sec of invincibility",
  },
  UNIQUE: {
    IED_B: "Attacks ignore 35% Monster DEF",
    IED_A: "Attacks ignore 40% Monster DEF",
    IED_C: "Attacks ignore 30% Monster DEF",
    BOSS_C: "Boss Damage: +30%",
    BOSS_B: "Boss Damage: +35%",
    BOSS_A: "Boss Damage: +40%",
    CRITDMG_A: "Critical Damage: +3%",
    CRITDMG_B: "Critical Damage: +2%",
    LARGE_DROP_MESO: "Increases Item and Meso Drop Rate by a large amount (50)",
    SMALL_DROP: "Item Acquisition Rate: +10%",
    FLAT_MESO: "Mesos Obtained: +10",
    FLAT_MAINSTAT_A: "STR: +8",
    FLAT_MAINSTAT_B: "STR: +7",
    DAMAGE_A: "Total Damage: +6%",
    DAMAGE_B: "Total Damage: +5%",
    INVIN: "When hit, gain +3 sec of invincibility",
  },
  LEGENDARY: {
    IED_B: "Attacks ignore 45% Monster DEF",
    IED_A: "Attacks ignore 50% Monster DEF",
    BOSS_C: "Boss Damage: +40%",
    BOSS_B: "Boss Damage: +45%",
    BOSS_A: "Boss Damage: +50%",
    CRITDMG_A: "Critical Damage: +6%",
    SMALL_DROP: "Item Acquisition Rate: +12%",
    FLAT_MESO: "Mesos Obtained: +12",
    DAMAGE_A: "Total Damage: +9%",
    INVIN: "When hit, gain +4 sec of invincibility",
  },
}

red_card_estimate = {
  RED_FAM_CARD: {
    FAMILIAR_STATS: percent({
      BASE: [],
      COMMON: [],
      RARE: [],
      EPIC: [],
      UNIQUE: [
        [LARGE_DROP_MESO, 54 / 2903 * 100],
        [INVIN, 33 / 2903 * 100],
        [CRITDMG_B, 22 / 2903 * 100],
        [CRITDMG_A, 17 / 2903 * 100],
        [FLAT_MESO, 16 / 2903 * 100],
        [DAMAGE_A, 9 / 2903 * 100],
        [IED_B, 7 / 2903 * 100],
        [BOSS_C, 7 / 2903 * 100],
        [SMALL_DROP, 6 / 2903 * 100],
        [BOSS_B, 6 / 2903 * 100],
        [IED_C, 6 / 2903 * 100],
        [DAMAGE_B, 6 / 2903 * 100],
        [IED_A, 3 / 2903 * 100],
      ],
      LEGENDARY: [
        [INVIN, 88 / 2903 * 100],
        [CRITDMG_A, 34 / 2903 * 100],
        [IED_B, 23 / 2903 * 100],
        [FLAT_MESO, 23 / 2903 * 100],
        [BOSS_A, 22 / 2903 * 100],
        [DAMAGE_A, 20 / 2903 * 100],
        [BOSS_C, 18 / 2903 * 100],
        [SMALL_DROP, 17 / 2903 * 100],
        [BOSS_B, 16 / 2903 * 100],
        [IED_A, 15 / 2903 * 100],
      ],
    }),
  },
}
