# this file was automatically generated by /data/familiars/run.sh
# do not edit, edit the scraper
import sys
from datautils import percent
from common import *

familiars = {
  FAMILIAR: {
    FAMILIAR_STATS: percent({
      BASE: [
      ],
      COMMON: [
        [IED_C, 0.617], # 15
        [SMALL_DROP, 1.235], # 30
        [SMALL_MESO, 1.235], # 30
        [DAMAGE_A, 0.37], # 1
      ],
      RARE: [
        [IED_C, 0.264], # 15
        [DROP_A, 0.88], # 50
        [SMALL_DROP, 0.88], # 30
        [SMALL_DROP_MESO, 0.88], # 20
        [MESO_A, 0.88], # 50
        [SMALL_MESO, 0.88], # 30
        [DAMAGE_A, 0.264], # 2
        [INVIN, 0.44], # 1
      ],
      EPIC: [
        [IED_A, 0.22], # 30
        [IED_C, 0.22], # 20
        [BOSS_C, 0.147], # 20
        [BOSS_A, 0.147], # 30
        [DROP_A, 0.734], # 60
        [LARGE_DROP, 0.734], # 100
        [DROP_MESO, 0.734], # 40
        [SMALL_DROP_MESO, 0.734], # 25
        [MESO_A, 0.734], # 60
        [LARGE_MESO, 0.734], # 100
        [DAMAGE_A, 0.22], # 3
        [INVIN, 0.367], # 2
      ],
      UNIQUE: [
        [IED_B, 0.219], # 35
        [IED_A, 0.219], # 40
        [IED_C, 0.219], # 30
        [BOSS_C, 0.146], # 30
        [BOSS_B, 0.146], # 35
        [BOSS_A, 0.146], # 40
        [CRITDMG_A, 0.438], # 3
        [CRITDMG_B, 0.438], # 2
        [LARGE_DROP_MESO, 0.73], # 50
        [SMALL_DROP, 0.365], # 10
        [FLAT_MESO, 0.365], # 10
        [DAMAGE_A, 0.219], # 6
        [DAMAGE_B, 0.219], # 5
        [INVIN, 0.365], # 3
      ],
      LEGENDARY: [
        [IED_B, 1.456], # 45
        [IED_A, 1.456], # 50
        [BOSS_C, 0.971], # 40
        [BOSS_B, 0.971], # 45
        [BOSS_A, 0.971], # 50
        [CRITDMG_A, 2.912], # 6
        [SMALL_DROP, 2.427], # 12
        [FLAT_MESO, 2.427], # 12
        [DAMAGE_A, 1.456], # 9
        [INVIN, 2.427], # 4
      ],
    }),
  },
}

values = {
  BASE: {
    ANY: 1,
  },
  COMMON: {
    ANY: 1,
    IED_C: 15,
    SMALL_DROP: 30,
    SMALL_MESO: 30,
    DAMAGE_A: 1,
  },
  RARE: {
    ANY: 1,
    IED_C: 15,
    DROP_A: 50,
    SMALL_DROP: 30,
    SMALL_DROP_MESO: 20,
    MESO_A: 50,
    SMALL_MESO: 30,
    DAMAGE_A: 2,
    INVIN: 1,
  },
  EPIC: {
    ANY: 1,
    IED_A: 30,
    IED_C: 20,
    BOSS_C: 20,
    BOSS_A: 30,
    DROP_A: 60,
    LARGE_DROP: 100,
    DROP_MESO: 40,
    SMALL_DROP_MESO: 25,
    MESO_A: 60,
    LARGE_MESO: 100,
    DAMAGE_A: 3,
    INVIN: 2,
  },
  UNIQUE: {
    ANY: 1,
    IED_B: 35,
    IED_A: 40,
    IED_C: 30,
    BOSS_C: 30,
    BOSS_B: 35,
    BOSS_A: 40,
    CRITDMG_A: 3,
    CRITDMG_B: 2,
    LARGE_DROP_MESO: 50,
    SMALL_DROP: 10,
    FLAT_MESO: 10,
    DAMAGE_A: 6,
    DAMAGE_B: 5,
    INVIN: 3,
  },
  LEGENDARY: {
    ANY: 1,
    IED_B: 45,
    IED_A: 50,
    BOSS_C: 40,
    BOSS_B: 45,
    BOSS_A: 50,
    CRITDMG_A: 6,
    SMALL_DROP: 12,
    FLAT_MESO: 12,
    DAMAGE_A: 9,
    INVIN: 4,
  },
}
red_card_estimate = {
  RED_FAM_CARD: {
    FAMILIAR_STATS: percent({
      BASE: [],
      COMMON: [],
      RARE: [],
      EPIC: [],
      UNIQUE: [
        [LARGE_DROP_MESO, 54 / 2903 * 100],
        [INVIN, 33 / 2903 * 100],
        [CRITDMG_B, 22 / 2903 * 100],
        [CRITDMG_A, 17 / 2903 * 100],
        [FLAT_MESO, 16 / 2903 * 100],
        [DAMAGE_A, 9 / 2903 * 100],
        [IED_B, 7 / 2903 * 100],
        [BOSS_C, 7 / 2903 * 100],
        [SMALL_DROP, 6 / 2903 * 100],
        [BOSS_B, 6 / 2903 * 100],
        [IED_C, 6 / 2903 * 100],
        [DAMAGE_B, 6 / 2903 * 100],
        [IED_A, 3 / 2903 * 100],
      ],
      LEGENDARY: [
        [INVIN, 88 / 2903 * 100],
        [CRITDMG_A, 34 / 2903 * 100],
        [IED_B, 23 / 2903 * 100],
        [FLAT_MESO, 23 / 2903 * 100],
        [BOSS_A, 22 / 2903 * 100],
        [DAMAGE_A, 20 / 2903 * 100],
        [BOSS_C, 18 / 2903 * 100],
        [SMALL_DROP, 17 / 2903 * 100],
        [BOSS_B, 16 / 2903 * 100],
        [IED_A, 15 / 2903 * 100],
      ],
    }),
  },
}
