# this file was automatically generated by /data/tms/run.sh
# do not edit, edit the scraper
import sys
from datautils import percent
from common import *

event = {
  VIOLET | EQUALITY: {
    HAT | TOP_OVERALL | BOTTOM | GLOVE | CAPE_BELT_SHOULDER: percent({
      RARE: [
        [FLAT_MAINSTAT_A, 6.0],
        [FLAT_HP_A, 10.0],
        [MAINSTAT_A, 6.0],
        [HP, 6.0],
        [FLAT_ALLSTAT_A, 4.0],
      ],
    }),
    SHOE: percent({
      RARE: [
        [FLAT_MAINSTAT_A, 5.56],
        [FLAT_HP_A, 9.25],
        [MAINSTAT_A, 5.56],
        [HP, 5.56],
        [FLAT_ALLSTAT_A, 3.7],
      ],
      EPIC: [
        [MAINSTAT_A, 11.9],
        [HP, 16.67],
        [ALLSTAT, 4.76],
      ],
      UNIQUE: [
        [MAINSTAT_A, 7.94],
        [HP, 9.52],
        [ALLSTAT, 6.35],
      ],
      LEGENDARY: [
        [DECENT_COMBAT_ORDERS, 6.25],
        [MAINSTAT_A, 8.33],
        [HP, 8.33],
        [ALLSTAT, 6.25],
      ],
    }),
    FACE_EYE_RING_EARRING_PENDANT: percent({
      RARE: [
        [FLAT_MAINSTAT_A, 6.0],
        [FLAT_HP_A, 10.0],
        [MAINSTAT_A, 6.0],
        [HP, 6.0],
        [FLAT_ALLSTAT_A, 4.0],
      ],
      EPIC: [
        [MAINSTAT_A, 11.9],
        [HP, 16.67],
        [ALLSTAT, 4.76],
      ],
      UNIQUE: [
        [MAINSTAT_A, 9.8],
        [HP, 11.76],
        [ALLSTAT, 7.84],
      ],
      LEGENDARY: [
        [MAINSTAT_A, 7.84],
        [HP, 7.84],
        [ALLSTAT, 5.88],
        [MESO_A, 5.88],
        [DROP_A, 5.88],
      ],
    }),
    WEAPON | EMBLEM | SECONDARY: percent({
      RARE: [
        [FLAT_MAINSTAT_A, 5.56],
        [FLAT_HP_A, 11.11],
        [FLAT_ATT_A, 3.7],
        [MAINSTAT_A, 5.56],
        [ATT, 1.85],
        [DAMAGE_A, 1.85],
        [FLAT_ALLSTAT_A, 3.7],
        [IED_C, 1.85],
      ],
      EPIC: [
        [ATT, 4.0],
        [DAMAGE_A, 4.0],
        [IED_C, 4.0],
        [MAINSTAT_A, 10.0],
        [HP, 14.0],
        [ALLSTAT, 4.0],
      ],
    }),
    FORCE_SHIELD_SOUL_RING: percent({
      RARE: [
        [FLAT_MAINSTAT_A, 6.25],
        [FLAT_HP_A, 12.5],
        [FLAT_ATT_A, 4.17],
        [MAINSTAT_A, 6.25],
        [ATT, 2.08],
        [DAMAGE_A, 2.08],
        [FLAT_ALLSTAT_A, 4.17],
        [IED_C, 2.08],
      ],
      EPIC: [
        [ATT, 4.65],
        [DAMAGE_A, 4.65],
        [IED_C, 4.65],
        [MAINSTAT_A, 11.63],
        [HP, 16.28],
        [ALLSTAT, 4.65],
      ],
    }),
    HAT | BOTTOM | CAPE_BELT_SHOULDER: percent({
      EPIC: [
        [MAINSTAT_A, 11.9],
        [HP, 16.67],
        [ALLSTAT, 4.76],
      ],
    }),
    TOP_OVERALL: percent({
      EPIC: [
        [INVIN, 12.5],
        [MAINSTAT_A, 10.42],
        [HP, 14.58],
        [ALLSTAT, 4.17],
      ],
      UNIQUE: [
        [INVIN, 5.48],
        [MAINSTAT_A, 6.85],
        [HP, 8.22],
        [ALLSTAT, 5.48],
      ],
      LEGENDARY: [
        [INVIN, 5.88],
        [MAINSTAT_A, 7.84],
        [HP, 7.84],
        [ALLSTAT, 5.88],
      ],
    }),
    GLOVE: percent({
      EPIC: [
        [MAINSTAT_A, 10.42],
        [HP, 14.58],
        [ALLSTAT, 4.17],
      ],
      UNIQUE: [
        [MAINSTAT_PER_10_LVLS, 1.49],
        [DECENT_SHARP_EYES, 5.97],
        [MAINSTAT_A, 7.46],
        [HP, 8.96],
        [ALLSTAT, 5.97],
      ],
      LEGENDARY: [
        [CRITDMG_A, 7.69],
        [DECENT_SPEED_INFUSION, 5.77],
        [MAINSTAT_A, 7.69],
        [HP, 7.69],
        [ALLSTAT, 5.77],
      ],
    }),
    HAT: percent({
      UNIQUE: [
        [MAINSTAT_A, 7.94],
        [HP, 9.52],
        [ALLSTAT, 6.35],
      ],
      LEGENDARY: [
        [COOLDOWN_1, 5.66],
        [COOLDOWN_2, 3.77],
        [MAINSTAT_A, 7.55],
        [HP, 7.55],
        [ALLSTAT, 5.66],
      ],
    }),
    BOTTOM: percent({
      UNIQUE: [
        [MAINSTAT_A, 7.94],
        [HP, 9.52],
        [ALLSTAT, 6.35],
      ],
      LEGENDARY: [
        [MAINSTAT_A, 8.89],
        [HP, 8.89],
        [ALLSTAT, 6.67],
      ],
    }),
    CAPE_BELT_SHOULDER: percent({
      UNIQUE: [
        [MAINSTAT_A, 8.47],
        [HP, 10.17],
        [ALLSTAT, 6.78],
      ],
      LEGENDARY: [
        [MAINSTAT_A, 8.89],
        [HP, 8.89],
        [ALLSTAT, 6.67],
      ],
    }),
    WEAPON | SECONDARY | FORCE_SHIELD_SOUL_RING: percent({
      UNIQUE: [
        [ATT, 6.52],
        [DAMAGE_A, 6.52],
        [IED_C, 8.7],
        [BOSS_C, 6.52],
        [MAINSTAT_A, 10.87],
        [ALLSTAT, 10.87],
      ],
      LEGENDARY: [
        [ATT, 4.44],
        [DAMAGE_A, 4.44],
        [IED_B, 6.67],
        [IED_A, 6.67],
        [BOSS_C, 4.44],
        [BOSS_B, 4.44],
        [BOSS_A, 4.44],
        [ATT_PER_10_LVLS, 6.67],
        [MAINSTAT_A, 8.89],
        [ALLSTAT, 6.67],
      ],
    }),
    EMBLEM: percent({
      UNIQUE: [
        [ATT, 6.98],
        [DAMAGE_A, 6.98],
        [IED_C, 9.3],
        [MAINSTAT_A, 11.63],
        [ALLSTAT, 11.63],
      ],
      LEGENDARY: [
        [ATT, 5.13],
        [DAMAGE_A, 5.13],
        [IED_B, 7.69],
        [IED_A, 7.69],
        [ATT_PER_10_LVLS, 7.69],
        [MAINSTAT_A, 10.26],
        [ALLSTAT, 7.69],
      ],
    }),
  },
  UNI: {
    HAT | TOP_OVERALL | BOTTOM | GLOVE | CAPE_BELT_SHOULDER: percent({
      RARE: [
        [FLAT_MAINSTAT_A, 8.33],
        [FLAT_HP_A, 9.26],
        [MAINSTAT_A, 2.78],
        [HP, 2.78],
        [FLAT_ALLSTAT_A, 8.33],
      ],
    }),
    SHOE: percent({
      RARE: [
        [FLAT_MAINSTAT_A, 7.3],
        [FLAT_HP_A, 7.3],
        [MAINSTAT_A, 2.19],
        [HP, 2.19],
        [FLAT_ALLSTAT_A, 7.3],
      ],
      EPIC: [
        [MAINSTAT_A, 13.7],
        [HP, 13.7],
        [ALLSTAT, 1.37],
      ],
      UNIQUE: [
        [MAINSTAT_A, 6.33],
        [HP, 6.33],
        [ALLSTAT, 1.27],
      ],
      LEGENDARY: [
        [DECENT_COMBAT_ORDERS, 10.91],
        [MAINSTAT_A, 7.27],
        [HP, 7.27],
        [ALLSTAT, 1.82],
      ],
    }),
    FACE_EYE_RING_EARRING_PENDANT: percent({
      RARE: [
        [FLAT_MAINSTAT_A, 8.33],
        [FLAT_HP_A, 9.26],
        [MAINSTAT_A, 2.78],
        [HP, 2.78],
        [FLAT_ALLSTAT_A, 8.33],
      ],
      EPIC: [
        [MAINSTAT_A, 13.7],
        [HP, 13.7],
        [ALLSTAT, 1.37],
      ],
      UNIQUE: [
        [MAINSTAT_A, 11.63],
        [HP, 11.63],
        [ALLSTAT, 2.33],
      ],
      LEGENDARY: [
        [MAINSTAT_A, 6.06],
        [HP, 6.06],
        [ALLSTAT, 1.52],
        [MESO_A, 9.09],
        [DROP_A, 9.09],
      ],
    }),
    WEAPON | EMBLEM | SECONDARY: percent({
      RARE: [
        [FLAT_MAINSTAT_A, 7.41],
        [FLAT_HP_A, 7.41],
        [FLAT_ATT_A, 3.7],
        [MAINSTAT_A, 5.56],
        [ATT, 1.85],
        [DAMAGE_A, 1.85],
        [FLAT_ALLSTAT_A, 3.7],
        [IED_C, 1.85],
      ],
      EPIC: [
        [ATT, 4.11],
        [DAMAGE_A, 4.11],
        [IED_C, 6.85],
        [MAINSTAT_A, 9.59],
        [HP, 9.59],
        [ALLSTAT, 8.22],
      ],
    }),
    FORCE_SHIELD_SOUL_RING: percent({
      RARE: [
        [FLAT_MAINSTAT_A, 8.0],
        [FLAT_HP_A, 8.0],
        [FLAT_ATT_A, 4.0],
        [MAINSTAT_A, 6.0],
        [ATT, 2.0],
        [DAMAGE_A, 2.0],
        [FLAT_ALLSTAT_A, 4.0],
        [IED_C, 2.0],
      ],
      EPIC: [
        [ATT, 4.55],
        [DAMAGE_A, 4.55],
        [IED_C, 7.58],
        [MAINSTAT_A, 10.61],
        [HP, 10.61],
        [ALLSTAT, 9.09],
      ],
    }),
    HAT | BOTTOM | CAPE_BELT_SHOULDER: percent({
      EPIC: [
        [MAINSTAT_A, 14.08],
        [HP, 14.08],
        [ALLSTAT, 1.41],
      ],
    }),
    TOP_OVERALL: percent({
      EPIC: [
        [INVIN, 5.6],
        [MAINSTAT_A, 13.08],
        [HP, 13.08],
        [ALLSTAT, 0.93],
      ],
      UNIQUE: [
        [INVIN, 8.16],
        [MAINSTAT_A, 4.08],
        [HP, 4.08],
        [ALLSTAT, 1.02],
      ],
      LEGENDARY: [
        [INVIN, 12.31],
        [MAINSTAT_A, 6.15],
        [HP, 6.15],
        [ALLSTAT, 1.54],
      ],
    }),
    GLOVE: percent({
      EPIC: [
        [MAINSTAT_A, 13.08],
        [HP, 13.08],
        [ALLSTAT, 0.93],
      ],
      UNIQUE: [
        [MAINSTAT_PER_10_LVLS, 5.26],
        [DECENT_SHARP_EYES, 8.42],
        [MAINSTAT_A, 5.26],
        [HP, 5.26],
        [ALLSTAT, 1.05],
      ],
      LEGENDARY: [
        [CRITDMG_A, 2.9],
        [DECENT_SPEED_INFUSION, 11.59],
        [MAINSTAT_A, 5.8],
        [HP, 5.8],
        [ALLSTAT, 1.45],
      ],
    }),
    HAT: percent({
      UNIQUE: [
        [MAINSTAT_A, 5.8],
        [HP, 5.8],
        [ALLSTAT, 1.45],
      ],
      LEGENDARY: [
        [COOLDOWN_1, 10.0],
        [COOLDOWN_2, 10.0],
        [MAINSTAT_A, 5.0],
        [HP, 5.0],
        [ALLSTAT, 1.25],
      ],
    }),
    BOTTOM: percent({
      UNIQUE: [
        [MAINSTAT_A, 6.35],
        [HP, 6.35],
        [ALLSTAT, 1.59],
      ],
      LEGENDARY: [
        [MAINSTAT_A, 8.89],
        [HP, 8.89],
        [ALLSTAT, 2.22],
      ],
    }),
    CAPE_BELT_SHOULDER: percent({
      UNIQUE: [
        [MAINSTAT_A, 7.69],
        [HP, 7.69],
        [ALLSTAT, 1.54],
      ],
      LEGENDARY: [
        [MAINSTAT_A, 8.89],
        [HP, 8.89],
        [ALLSTAT, 6.67],
      ],
    }),
    WEAPON | SECONDARY | FORCE_SHIELD_SOUL_RING: percent({
      UNIQUE: [
        [ATT, 8.22],
        [DAMAGE_A, 16.44],
        [IED_C, 20.55],
        [BOSS_C, 5.48],
        [MAINSTAT_A, 2.74],
        [ALLSTAT, 2.74],
      ],
      LEGENDARY: [
        [ATT, 3.24],
        [DAMAGE_A, 16.18],
        [IED_B, 25.89],
        [IED_A, 16.18],
        [BOSS_C, 3.07],
        [BOSS_B, 2.1],
        [BOSS_A, 1.13],
        [ATT_PER_10_LVLS, 1.13],
        [MAINSTAT_A, 1.13],
        [ALLSTAT, 1.13],
      ],
    }),
    EMBLEM: percent({
      UNIQUE: [
        [ATT, 8.7],
        [DAMAGE_A, 17.39],
        [IED_C, 21.74],
        [MAINSTAT_A, 2.9],
        [ALLSTAT, 2.9],
      ],
      LEGENDARY: [
        [ATT, 3.45],
        [DAMAGE_A, 17.27],
        [IED_B, 27.63],
        [IED_A, 17.27],
        [ATT_PER_10_LVLS, 1.21],
        [MAINSTAT_A, 1.21],
        [ALLSTAT, 1.21],
      ],
    }),
  },
}
