header() {
  script=$(realpath "$0" | sed "s|$(realpath ../../)||g")
  echo "# this file was automatically generated by $script"
  echo "# do not edit, edit the scraper"
  echo "import sys"
  echo "from datautils import percent"
  echo "from common import *"
  echo
}
